import Foundation

/// Static catalog of every category and role profile. Single source of truth.
public enum Catalog {

    public static let categories: [CleanCategory] = [
        .init(id: "trash", name: "Trash",
              detail: "Files you already threw away.",
              consequence: "Frees the space for good. Items can no longer be restored.",
              risk: .safe, systemImage: "trash"),
        .init(id: "logs", name: "Log files",
              detail: "Diagnostic text files apps write while running.",
              consequence: "Nothing changes for you. Apps write new logs as needed.",
              risk: .safe, systemImage: "doc.plaintext"),
        .init(id: "user-caches", name: "App caches",
              detail: "Temporary data apps keep to start faster.",
              consequence: "Apps may open a little slower once while they rebuild it.",
              risk: .review, systemImage: "archivebox"),
        .init(id: "xcode-derived", name: "Xcode build data",
              detail: "Intermediate build products (DerivedData).",
              consequence: "Next build of each project takes longer, one time.",
              risk: .safe, systemImage: "hammer"),
        .init(id: "device-support", name: "iOS device support",
              detail: "Debug symbols for iPhones/iPads you connected before.",
              consequence: "Re-downloaded automatically next time you plug that device in.",
              risk: .review, systemImage: "iphone"),
        .init(id: "simulators", name: "Simulator caches",
              detail: "Caches and unavailable simulator runtimes.",
              consequence: "Simulators rebuild caches; removed runtimes re-download on demand.",
              risk: .review, systemImage: "ipad.and.iphone"),
        .init(id: "npm-cache", name: "JavaScript package caches",
              detail: "npm / yarn / pnpm download caches.",
              consequence: "Next install re-downloads packages from the internet.",
              risk: .safe, systemImage: "shippingbox"),
        .init(id: "pip-cache", name: "Python package cache",
              detail: "pip's download cache.",
              consequence: "Next pip install re-downloads packages.",
              risk: .safe, systemImage: "shippingbox"),
        .init(id: "brew-cache", name: "Homebrew cache",
              detail: "Old installer files Homebrew already used.",
              consequence: "Nothing changes; brew re-downloads if ever needed.",
              risk: .safe, systemImage: "mug"),
        .init(id: "cocoapods-cache", name: "CocoaPods cache",
              detail: "Downloaded pod sources.",
              consequence: "Next pod install re-downloads them.",
              risk: .safe, systemImage: "shippingbox"),
        .init(id: "rust-cache", name: "Rust crates & toolchains",
              detail: "Cargo's downloaded crate registry and the Rust toolchains rustup installed.",
              consequence: "Crates re-download on the next build. Removing a toolchain means rustup downloads it again (~400 MB each).",
              risk: .review, systemImage: "shippingbox"),
        .init(id: "go-cache", name: "Go modules & build cache",
              detail: "Downloaded Go modules and the compiler's build cache.",
              consequence: "Next build re-downloads modules and recompiles from scratch, one time.",
              risk: .safe, systemImage: "shippingbox"),
        .init(id: "cli-old-versions", name: "Old CLI tool versions",
              detail: "Previous releases of self-updating command-line tools (Claude Code, Cursor Agent, Copilot CLI) that install side by side and never clean up. The version currently in use is never listed.",
              consequence: "Nothing changes — you keep running the current version. You just can't roll back to an older one without reinstalling it.",
              risk: .safe, systemImage: "terminal"),
        .init(id: "editor-caches", name: "Editor caches",
              detail: "Cache and cached-data folders of VS Code, Cursor, Windsurf and JetBrains IDEs — not your settings or extensions.",
              consequence: "Editors rebuild these on next launch; your settings, extensions and projects are untouched.",
              risk: .safe, systemImage: "chevron.left.forwardslash.chevron.right"),
        .init(id: "gradle-cache", name: "Gradle / Maven caches",
              detail: "Java build tool dependency caches.",
              consequence: "Next build re-downloads dependencies (can be slow on big projects).",
              risk: .review, systemImage: "shippingbox"),
        // Docker — granular categories, cleaned through the docker CLI itself.
        // Docker has no Trash: removal is permanent, so every consequence says so.
        .init(id: "docker-build-cache", name: "Docker build cache",
              detail: "Layers Docker kept from previous image builds and no build is using.",
              consequence: "Removed by Docker itself — not the Trash. Next build is slower, one time.",
              risk: .safe, systemImage: "cube.transparent", removal: .external),
        .init(id: "docker-dangling-images", name: "Docker dangling images",
              detail: "Untagged leftover images from old builds. Nothing references them.",
              consequence: "Removed by Docker itself — not the Trash. Rebuilt automatically if a build needs them.",
              risk: .safe, systemImage: "cube", removal: .external),
        .init(id: "docker-stopped-containers", name: "Docker stopped containers",
              detail: "Containers that exited and were never removed.",
              consequence: "Removed by Docker — not the Trash. Their local changes and logs are gone; images stay.",
              risk: .review, systemImage: "shippingbox", removal: .external),
        .init(id: "docker-unused-images", name: "Docker unused images",
              detail: "Tagged images no container is using.",
              consequence: "Removed by Docker — not the Trash. Getting one back means re-pulling or rebuilding it.",
              risk: .review, systemImage: "cube.box", removal: .external),
        .init(id: "docker-unused-volumes", name: "Docker unused volumes",
              detail: "Volumes not attached to any container. May hold real data (databases!).",
              consequence: "Removed by Docker — not the Trash. Data inside the volume is gone for good.",
              risk: .risky, systemImage: "externaldrive.fill", removal: .external),
        .init(id: "docker-data", name: "Docker disk image",
              detail: "The virtual disk holding ALL Docker images, containers and volumes. Shown only when Docker is not running (start Docker to review its contents item by item).",
              consequence: "Deletes every local container and volume. Only clean if you accept rebuilding everything.",
              risk: .risky, systemImage: "cube.box"),
        .init(id: "container-vm-disks", name: "Container VM disks",
              detail: "The virtual disk files behind Colima, Lima, Podman, OrbStack or Rancher Desktop — often the single biggest file on a developer's Mac.",
              consequence: "Deleting one loses every image, container and volume inside that VM. Note: these files do not shrink when you prune Docker, so pruning frees space inside the VM but not on your disk.",
              risk: .risky, systemImage: "externaldrive.connected.to.line.below"),
        .init(id: "orphaned-app-data", name: "Leftovers from deleted apps",
              detail: "Settings, caches and support files belonging to apps that are no longer installed.",
              consequence: "Nothing changes for apps you still have. If you reinstall one of these, it starts fresh.",
              risk: .review, systemImage: "app.badge.checkmark"),
        .init(id: "ai-models", name: "Local AI models",
              detail: "Downloaded model weights: Ollama, LM Studio, Hugging Face, PyTorch, Whisper.",
              consequence: "Tools re-download a model next time you use it — some are tens of GB.",
              risk: .review, systemImage: "brain"),
        .init(id: "adobe-media-cache", name: "Adobe media cache",
              detail: "Preview/render cache from Premiere, After Effects, Audition.",
              consequence: "Projects re-render previews next time you open them.",
              risk: .review, systemImage: "film"),
        .init(id: "font-caches", name: "Font caches",
              detail: "System font cache files.",
              consequence: "Rebuilt automatically; first launch of some apps may be slower once.",
              risk: .safe, systemImage: "textformat"),
        .init(id: "sketch-cache", name: "Design app caches",
              detail: "Sketch and Figma desktop caches.",
              consequence: "Apps rebuild caches; cloud files are untouched.",
              risk: .safe, systemImage: "paintbrush"),
        .init(id: "fcp-render", name: "Final Cut render files",
              detail: "Render files inside your Final Cut libraries.",
              consequence: "Final Cut re-renders those sections when you open the project.",
              risk: .review, systemImage: "film.stack"),
        .init(id: "screen-recordings", name: "Screen recordings",
              detail: "Screen Recording files on Desktop and in Movies.",
              consequence: "Gone once Trash is emptied — keep any you still need.",
              risk: .review, systemImage: "record.circle"),
        .init(id: "browser-caches", name: "Browser caches",
              detail: "Cached pages and images from Safari, Chrome, Firefox, Edge.",
              consequence: "Websites load a little slower on first visit. You stay logged in.",
              risk: .review, systemImage: "globe"),
        .init(id: "zoom-teams-cache", name: "Meeting app caches",
              detail: "Zoom and Microsoft Teams temporary data and old installers.",
              consequence: "Apps rebuild caches on next launch.",
              risk: .review, systemImage: "video"),
        .init(id: "chat-app-caches", name: "Chat app caches",
              detail: "Cached images, files and service-worker data from Slack, Discord, Telegram and Signal — the cache folders only, never the message stores.",
              consequence: "Apps re-download attachments and images you scroll back to. You stay logged in and no messages are lost.",
              risk: .review, systemImage: "message"),
        .init(id: "old-downloads", name: "Old downloads",
              detail: "Files in Downloads untouched for over 90 days.",
              consequence: "Check the list first — anything you still need, keep it.",
              risk: .review, systemImage: "arrow.down.circle"),
        .init(id: "desktop-screenshots", name: "Screenshots",
              detail: "Screenshot files sitting on your Desktop.",
              consequence: "Gone once Trash is emptied — keep any you still need.",
              risk: .review, systemImage: "camera.viewfinder"),
        .init(id: "mail-downloads", name: "Mail attachments cache",
              detail: "Copies of attachments Mail already opened.",
              consequence: "Originals stay in your emails; Mail re-downloads on open.",
              risk: .review, systemImage: "envelope"),
        .init(id: "large-files", name: "Large files",
              detail: "Files over 500 MB in Downloads, Desktop, Documents, Movies.",
              consequence: "These are YOUR files. Only clean what you are sure about.",
              risk: .risky, systemImage: "doc.zipper"),
        .init(id: "ios-backups", name: "iPhone/iPad backups",
              detail: "Local device backups stored by Finder/iTunes.",
              consequence: "You lose the ability to restore that device from this Mac.",
              risk: .risky, systemImage: "externaldrive.badge.icloud"),
    ]

    public static let roles: [RoleProfile] = [
        .init(id: "developer", name: "Developer",
              blurb: "Build caches, package managers, Xcode leftovers.",
              systemImage: "hammer.fill",
              categoryIDs: ["xcode-derived", "device-support", "simulators", "npm-cache",
                            "pip-cache", "brew-cache", "cocoapods-cache", "gradle-cache",
                            "rust-cache", "go-cache", "cli-old-versions", "editor-caches",
                            "docker-build-cache", "docker-dangling-images",
                            "docker-stopped-containers", "docker-unused-images",
                            "docker-unused-volumes", "docker-data", "container-vm-disks",
                            "ai-models", "orphaned-app-data", "user-caches",
                            "logs", "trash"]),
        .init(id: "artist", name: "Designer / Artist",
              blurb: "Adobe & design app caches, big old files.",
              systemImage: "paintpalette.fill",
              categoryIDs: ["adobe-media-cache", "sketch-cache", "font-caches",
                            "ai-models", "user-caches", "large-files",
                            "old-downloads", "trash"]),
        .init(id: "video", name: "Video creator",
              blurb: "Render files, media caches, screen recordings.",
              systemImage: "video.fill",
              categoryIDs: ["adobe-media-cache", "fcp-render", "screen-recordings",
                            "large-files", "old-downloads", "user-caches", "trash"]),
        .init(id: "office", name: "Office work",
              blurb: "Old downloads, mail attachments, browser data.",
              systemImage: "doc.text.fill",
              categoryIDs: ["old-downloads", "mail-downloads", "browser-caches",
                            "chat-app-caches", "desktop-screenshots",
                            "orphaned-app-data", "user-caches", "logs", "trash"]),
        .init(id: "marketing", name: "Marketing",
              blurb: "Browser caches, meeting apps, screenshots, media.",
              systemImage: "megaphone.fill",
              categoryIDs: ["browser-caches", "zoom-teams-cache", "chat-app-caches",
                            "old-downloads", "desktop-screenshots", "large-files",
                            "user-caches", "trash"]),
        .init(id: "general", name: "Everyday use",
              blurb: "A sensible clean-up for any Mac.",
              systemImage: "person.fill",
              categoryIDs: ["user-caches", "logs", "browser-caches", "old-downloads",
                            "orphaned-app-data", "cli-old-versions", "ai-models",
                            "trash", "large-files", "ios-backups"]),
    ]

    /// Cross-role sweep: every category, biggest win first. Not part of `roles`
    /// (it isn't a person's job — it's "look everywhere"), but selectable as its
    /// own tab and paired with the one-click quick clean.
    public static let smartRole = RoleProfile(
        id: "smart", name: "Smart Clean",
        blurb: "Look everywhere, then clean the safe wins in one click.",
        systemImage: "wand.and.stars",
        categoryIDs: categories.map(\.id)
    )

    /// Roles shown in the top tab bar: Smart Clean first, then the job profiles.
    public static var tabRoles: [RoleProfile] { [smartRole] + roles }

    public static func category(_ id: String) -> CleanCategory? {
        categories.first { $0.id == id }
    }
    public static func role(_ id: String) -> RoleProfile? {
        tabRoles.first { $0.id == id }
    }
}
